import {Layout, makeScene2D} from '@motion-canvas/2d';
import {all, waitFor, waitUntil} from '@motion-canvas/core';
import {loadFonts} from '../../../../../common/fonts';
import {theme} from '../../theme';
import {accent, background, foreground, heading, muted, text} from '../shared/drawing';
import {orderTable, sales, salesTable} from '../shared/records';
import {januaryTotals, monthlyChart, workloadExamples} from '../shared/workloads';
import {promotion, together} from './questions';

export default makeScene2D(function* (view) {
  view.fill(background);
  const title = heading('peki, ', 'bütün satışlara', ' bakarsak?');
  const previous = orderTable();
  previous.root.position([0, 85]);
  previous.rows[1].highlight.opacity(1);
  previous.rows[1].cells[1].text('preparing');
  previous.rows[1].cells[1].fill(accent);
  view.add([title, previous.root]);
  yield loadFonts();
  yield* waitFor(0.65);
  yield* all(previous.root.opacity(0, 0.35), title.opacity(0, 0.25));
  previous.root.remove();
  title.children(heading('ocakta hangi mağaza ', 'ne kadar sattı?').children());
  const table = salesTable();
  table.root.position([-430, 80]);
  table.root.opacity(0);
  const sql = new Layout({position: [95, -160], opacity: 0});
  const lines = [
    'SELECT store_id, SUM(amount)', 'FROM sales',
    "WHERE sold_at >= '2026-01-01'", "  AND sold_at < '2026-02-01'", 'GROUP BY store_id;',
  ].map((line, i) => text(line, 25, {position: [0, i * 38], offset: [-1, 0], fontFamily: theme.fontFamily.mono, fill: muted}));
  sql.add(lines);
  view.add([table.root, sql]);
  yield* all(title.opacity(1, 0.35), table.root.opacity(1, 0.5));
  yield* waitUntil('filter');
  yield* all(sql.opacity(1, 0.35), lines[2].fill(accent, 0.25), lines[3].fill(accent, 0.25), table.rows[5].root.opacity(0.2, 0.4), ...table.rows.slice(0, 5).map(row => row.cells[2].fill(accent, 0.3)));
  yield* waitUntil('group');
  yield* all(lines[2].fill(muted, 0.25), lines[3].fill(muted, 0.25), lines[4].fill(accent, 0.25), ...table.rows.slice(0, 5).map(row => row.cells[2].fill(foreground, 0.25)));
  const groups = new Layout({});
  const groupLabels = ['A', 'B'].map((store, i) => text(`mağaza ${store.toLowerCase()}`, 29, {position: [230 + i * 360, 135], fill: accent, opacity: 0}));
  groups.add(groupLabels);
  view.add(groups);
  yield* all(...groupLabels.map(label => label.opacity(1, 0.3)));
  const counters = [0, 0];
  const values = sales.slice(0, 5).map((row, i) => {
    const column = row.store === 'A' ? 0 : 1;
    const slot = counters[column]++;
    const node = text(String(row.amount), 34, {offset: [1, 0], fontFamily: theme.fontFamily.mono, opacity: 0});
    node.position([-430 + 202 + node.width(), 80 + table.rows[i].root.y()]);
    groups.add(node);
    return {node, target: [282 + column * 360, 199 + slot * 55] as [number, number]};
  });
  for (const {node, target} of values) {
    yield* node.opacity(1, 0.1);
    yield* node.position(target, 0.38);
  }
  yield* waitUntil('sum');
  yield* all(lines[4].fill(muted, 0.25), lines[0].fill(accent, 0.25));
  const totals = januaryTotals.map((amount, i) => text(`${amount} ₺`, 58, {position: [230 + i * 360, 257], fill: accent, fontFamily: theme.fontFamily.mono, opacity: 0}));
  groups.add(totals);
  yield* all(...values.map(({node}) => node.opacity(0, 0.3)));
  yield* all(...totals.map(total => total.opacity(1, 0.4)));
  yield* waitUntil('chart');
  yield* all(title.opacity(0, 0.2), table.root.opacity(0, 0.4), sql.opacity(0, 0.3), groups.opacity(0, 0.3));
  title.children(heading('bu işleme ', 'aggregation', ' diyoruz.').children());
  const chart = monthlyChart();
  chart.root.position([0, 35]);
  chart.root.scale(1.3);
  chart.root.opacity(0);
  const resultLabel = text('query result', 30, {position: [0, 330], fill: muted, fontFamily: theme.fontFamily.mono, opacity: 0});
  view.add([chart.root, resultLabel]);
  yield* all(title.opacity(1, 0.3), chart.root.opacity(1, 0.45), resultLabel.opacity(1, 0.35));
  yield* waitUntil('olap');
  yield* title.opacity(0, 0.2);
  title.children(heading('bu erişim biçimi: ', 'OLAP').children());
  const expansion = text('online analytical processing', 36, {position: [-806, -283], offset: [-1, 0], fill: muted, fontFamily: theme.fontFamily.mono, opacity: 0});
  view.add(expansion);
  yield* all(title.opacity(1, 0.3), expansion.opacity(1, 0.3));
  yield* waitUntil('promotion');
  yield* all(title.opacity(0, 0.2), expansion.opacity(0, 0.25), chart.root.opacity(0, 0.35), resultLabel.opacity(0, 0.25));
  title.children(heading('promosyonda ', 'ne kadar fazla', ' muz sattık?').children());
  const promo = promotion();
  view.add(promo);
  yield* all(title.opacity(1, 0.3), promo.opacity(1, 0.5));
  yield* waitUntil('together');
  yield* all(title.opacity(0, 0.2), promo.opacity(0, 0.35));
  title.children(heading('bu bebek beziyle ', 'en çok hangi mama', ' alınıyor?').children());
  const pair = together();
  view.add(pair.root);
  yield* all(title.opacity(1, 0.3), pair.root.opacity(1, 0.5));
  yield* pair.arrow.travel(0.8);
  yield* waitUntil('compare');
  yield* all(title.opacity(0, 0.2), pair.root.opacity(0, 0.4));
  title.children(heading('iki soru, ', 'iki erişim biçimi.').children());
  const examples = workloadExamples();
  examples.root.opacity(0);
  view.add(examples.root);
  yield* all(title.opacity(1, 0.3), examples.root.opacity(1, 0.5));
  yield* waitUntil('end');
});
