import {Layout, makeScene2D} from '@motion-canvas/2d';
import {all, waitFor, waitUntil} from '@motion-canvas/core';
import {loadFonts} from '../../../../../common/fonts';
import {cartoonArrow} from '../../../../../common/cartoon-arrow';
import {cartoonDatabase} from '../../../../../common/cartoon-system';
import {theme} from '../../theme';
import {accent, background, foreground, heading, muted, paper, text} from '../shared/drawing';
import {etlPipeline} from '../shared/etl-pipeline';
import {crmPipeline} from './crm-pipeline';

export default makeScene2D(function* (view) {
  view.fill(background);
  const title = heading('dönüşümü ', 'önce yapmak', ' şart mı?');
  const pipeline = etlPipeline();
  pipeline.fields.opacity(1);
  pipeline.region.opacity(1);
  pipeline.stored.opacity(1);
  view.add([title, pipeline.root]);
  yield loadFonts();
  yield* waitUntil('etl');
  const letters = ['E', 'T', 'L'].map((letter, i) => text(letter, 67, {position: [-60 + i * 60, -226], fill: i === 1 ? accent : foreground, fontFamily: theme.fontFamily.mono, opacity: 0}));
  view.add(letters);
  yield* all(...letters.map(letter => letter.opacity(1, 0.3)));
  yield* waitUntil('elt');
  yield* all(title.opacity(0, 0.2), pipeline.root.opacity(0, 0.4));
  title.children(heading('başka bir düzen: ', 'önce yükle.').children());
  yield* all(title.opacity(1, 0.3), letters[1].y(-263, 0.25), letters[2].y(-190, 0.25));
  yield* all(letters[1].x(60, 0.55), letters[2].x(0, 0.55));
  yield* all(letters[1].y(-226, 0.25), letters[2].y(-226, 0.25));
  const alternative = new Layout({opacity: 0});
  const source = cartoonDatabase('sales db', accent);
  source.root.position([-705, 100]);
  source.root.add([
    text('#1042', 27, {y: 0, fontFamily: theme.fontFamily.mono}),
    text('store A', 23, {y: 58, fill: accent, fontFamily: theme.fontFamily.mono}),
  ]);
  const copy = paper(240, 134, '#101315');
  copy.root.position([-225, 100]);
  copy.root.opacity(0.2);
  copy.root.add([
    text('#1042', 28, {y: -24, fontFamily: theme.fontFamily.mono}),
    text('store A', 26, {y: 27, fill: accent, fontFamily: theme.fontFamily.mono}),
  ]);
  const warehouse = cartoonDatabase('data warehouse', accent);
  warehouse.root.position([490, 100]);
  warehouse.root.scale(2);
  warehouse.caption.fontSize(19);
  const inside = paper(330, 136, '#101315');
  inside.root.position([490, 153]);
  inside.root.opacity(0);
  const value = text('#1042 · A', 31, {y: -25, fontFamily: theme.fontFamily.mono});
  const region = text('region: Marmara', 27, {y: 30, fill: accent, fontFamily: theme.fontFamily.mono, opacity: 0});
  inside.root.add([value, region]);
  const transformLabel = text('transform', 29, {position: [490, 43], fill: accent, opacity: 0});
  const extract = cartoonArrow('s11-elt-extract', [-550, 100], [-383, 100], accent, 0);
  const load = cartoonArrow('s11-elt-load', [-63, 100], [211, 100], accent, 0);
  alternative.add([source.root, copy.root, warehouse.root, inside.root, transformLabel, extract.root, load.root,
    text('extract', 26, {position: [-467, 20], opacity: () => extract.reveal()}),
    text('load', 26, {position: [74, 20], opacity: () => load.reveal()}),
  ]);
  view.add(alternative);
  yield* alternative.opacity(1, 0.5);
  yield* extract.reveal(1, 0.3);
  yield* extract.travel(0.7);
  yield* all(extract.arrive(), copy.root.opacity(1, 0.3));
  yield* load.reveal(1, 0.35);
  yield* load.travel(0.8);
  yield* all(load.arrive(), inside.root.opacity(1, 0.3));
  yield* waitUntil('transform');
  yield* title.opacity(0, 0.2);
  title.children(heading('sonra ', 'warehouse içinde', ' dönüştür.').children());
  yield* title.opacity(1, 0.3);
  yield* transformLabel.opacity(1, 0.3);
  yield* waitFor(0.6);
  yield* all(region.opacity(1, 0.4), inside.face.stroke(accent, 0.15).to(foreground, 0.4));
  yield* waitUntil('return');
  yield* all(title.opacity(0, 0.2), alternative.opacity(0, 0.4), ...letters.map(letter => letter.opacity(0, 0.3)));
  alternative.remove();
  title.children(heading('bizim örnekte ', 'ETL ile devam.').children());
  yield* all(title.opacity(1, 0.3), pipeline.root.opacity(1, 0.5));
  yield* waitUntil('crm');
  yield* all(title.opacity(0, 0.2), pipeline.root.opacity(0, 0.4));
  pipeline.root.remove();
  title.children(heading('bu kaynağa ', 'API üzerinden', ' erişiyoruz.').children());
  const crm = crmPipeline();
  crm.root.opacity(0);
  view.add(crm.root);
  yield* all(title.opacity(1, 0.3), crm.root.opacity(1, 0.5));
  yield* waitUntil('connector');
  yield* crm.request.reveal(1, 0.35);
  yield* crm.request.travel(0.7);
  yield* crm.request.arrive();
  yield* crm.response.reveal(1, 0.35);
  yield* crm.response.travel(0.7);
  yield* crm.response.arrive();
  yield* all(...crm.connector.lights.map(light => light.opacity(1, 0.15).to(0.65, 0.3)));
  yield* crm.load.reveal(1, 0.35);
  yield* crm.load.travel(0.7);
  yield* all(crm.load.arrive(), crm.customers.opacity(1, 0.3));
  yield* waitUntil('own-analysis');
  yield* title.opacity(0, 0.2);
  title.children(heading('analizi ', 'kendi sistemimizde', ' yapabiliriz.').children());
  yield* title.opacity(1, 0.3);
  yield* waitUntil('next');
  yield* all(title.opacity(0, 0.2), crm.root.opacity(0, 0.4));
  crm.root.remove();
  const choice = new Layout({opacity: 0});
  const operational = cartoonDatabase('transactions', accent);
  operational.root.position([-400, 70]);
  operational.root.scale(1.6);
  const analytical = cartoonDatabase('analytics', accent);
  analytical.root.position([400, 70]);
  analytical.root.scale(1.6);
  const link = cartoonArrow('s11-workload-separation', [-170, 70], [170, 70], accent);
  choice.add([operational.root, analytical.root, link.root, text('ETL', 30, {y: -15, fill: muted, fontFamily: theme.fontFamily.mono})]);
  view.add(choice);
  title.children(heading('ikisini ', 'tek sistemde', ' çalıştırsak?').children());
  yield* all(title.opacity(1, 0.3), choice.opacity(1, 0.5));
  yield* waitUntil('end');
});
