import {Layout, makeScene2D} from '@motion-canvas/2d';
import {all, waitUntil} from '@motion-canvas/core';
import {loadFonts} from '../../../../../common/fonts';
import {cartoonArrow} from '../../../../../common/cartoon-arrow';
import {cartoonDatabase} from '../../../../../common/cartoon-system';
import {theme} from '../../theme';
import {accent, background, heading, muted, paper, text} from '../shared/drawing';
import {analysisInputs, dataFile} from '../shared/data-files';
import {etlPipeline} from '../shared/etl-pipeline';
import {lakeConsumers, lakeStorage} from '../shared/lake-system';

export default makeScene2D(function* (view) {
  view.fill(background);
  const title = heading('bu girdileri ', 'nasıl saklayacağız?');
  const inputs = analysisInputs();
  view.add([title, inputs.root]);
  yield loadFonts();
  yield* waitUntil('files');
  yield* all(title.opacity(0, 0.2), inputs.root.opacity(0, 0.35));
  inputs.root.remove();
  title.children(heading('farklı biçimler, ', 'aynı saklama alanı.').children());
  const collection = paper(1100, 660, '#101315');
  collection.root.position([0, 90]);
  collection.root.opacity(0);
  collection.root.add(text('data lake', 37, {position: [-480, -276], offset: [-1, 0], fill: accent}));
  const collectionFiles = [dataFile('sales.parquet', 'records'), dataFile('reviews.json', 'review'), dataFile('product.jpg', 'image'), dataFile('readings.csv', 'sensor')];
  collectionFiles.forEach((file, i) => {
    file.root.position([-260 + (i % 2) * 520, -101 + Math.floor(i / 2) * 274]);
    file.root.scale(0.77);
    collection.root.add(file.root);
  });
  view.add(collection.root);
  yield* all(title.opacity(1, 0.3), collection.root.opacity(1, 0.5));
  yield* waitUntil('choose');
  yield* all(title.opacity(0, 0.2), collection.root.opacity(0, 0.4));
  collection.root.remove();
  const direct = etlPipeline();
  direct.fields.opacity(1);
  direct.region.opacity(1);
  direct.stored.opacity(1);
  direct.root.opacity(0);
  view.add(direct.root);
  title.children(heading('doğrudan warehouse’a ', 'gidebiliyorduk.').children());
  yield* all(title.opacity(1, 0.3), direct.root.opacity(1, 0.5));
  yield* waitUntil('insert-lake');
  yield* all(title.opacity(0, 0.2), direct.root.opacity(0, 0.4));
  direct.root.remove();
  title.children(heading('bu örnekte ', 'lake’i araya alıyoruz.').children());
  const ingest = new Layout({opacity: 0});
  const source = cartoonDatabase('sales db', accent);
  source.root.position([-570, 75]);
  source.root.scale(1.5);
  source.root.add([text('#1042', 30, {y: 0, fontFamily: theme.fontFamily.mono}), text('store A', 25, {y: 62, fill: accent, fontFamily: theme.fontFamily.mono})]);
  const storage = lakeStorage();
  storage.root.position([420, 75]);
  storage.files[0].root.opacity(0.18);
  storage.files[3].root.opacity(0.18);
  const copy = cartoonArrow('s14-sales-copy-to-lake', [-345, 75], [120, 75], accent, 0);
  const note = text('siparişin ürün satırlarını da taşıyoruz.', 31, {position: [0, 389], fill: muted, opacity: 0});
  ingest.add([source.root, storage.root, copy.root, note]);
  view.add(ingest);
  yield* all(title.opacity(1, 0.3), ingest.opacity(1, 0.5));
  yield* copy.reveal(1, 0.4);
  yield* copy.travel(0.8);
  yield* all(copy.arrive(), storage.files[0].root.opacity(1, 0.3), storage.files[3].root.opacity(1, 0.3), note.opacity(1, 0.3));
  yield* waitUntil('consumers');
  yield* all(title.opacity(0, 0.2), ingest.opacity(0, 0.4));
  ingest.remove();
  title.children(heading('her consumer ', 'kendi dönüşümünü', ' yapıyor.').children());
  const consumers = lakeConsumers();
  consumers.root.opacity(0);
  consumers.features.root.opacity(0);
  consumers.train.root.opacity(0);
  consumers.readFeatures.reveal(0);
  consumers.training.reveal(0);
  consumers.readSales.reveal(0);
  consumers.load.reveal(0);
  consumers.warehouse.root.opacity(0.22);
  view.add(consumers.root);
  yield* all(title.opacity(1, 0.3), consumers.root.opacity(1, 0.5));
  yield* consumers.readSales.reveal(1, 0.3);
  yield* consumers.readSales.travel(0.6);
  yield* consumers.readSales.arrive();
  yield* consumers.load.reveal(1, 0.3);
  yield* consumers.load.travel(0.6);
  yield* all(consumers.load.arrive(), consumers.warehouse.root.opacity(1, 0.3));
  yield* waitUntil('training');
  yield* all(consumers.features.root.opacity(1, 0.4), consumers.train.root.opacity(1, 0.4));
  yield* consumers.readFeatures.reveal(1, 0.3);
  yield* consumers.readFeatures.travel(0.6);
  yield* consumers.readFeatures.arrive();
  yield* consumers.training.reveal(1, 0.3);
  yield* consumers.training.travel(0.6);
  yield* consumers.training.arrive();
  yield* waitUntil('raw');
  yield* title.opacity(0, 0.2);
  title.children(heading('kaynak biçimini ', 'koruyabiliriz.').children());
  const sushi = text('sushi principle', 31, {position: [-540, 381], fill: accent, fontStyle: 'italic', opacity: 0});
  view.add(sushi);
  yield* all(title.opacity(1, 0.3), sushi.opacity(1, 0.3));
  yield* waitUntil('meaning');
  yield* all(title.opacity(0, 0.2), sushi.opacity(0, 0.2));
  title.children(heading('alanların anlamını ', 'yine bilmeliyiz.').children());
  const meaning = text('store A hangi mağaza?', 29, {position: [-540, 381], fill: muted, opacity: 0});
  view.add(meaning);
  yield* all(title.opacity(1, 0.3), meaning.opacity(1, 0.3));
  yield* waitUntil('next');
  yield* all(title.opacity(0, 0.2), meaning.opacity(0, 0.2));
  title.children(heading('peki, gelen kayıt ', 'eksikse?').children());
  yield* title.opacity(1, 0.3);
  yield* waitUntil('end');
});
