import {Layout, makeScene2D} from '@motion-canvas/2d';
import {all, waitUntil} from '@motion-canvas/core';
import {loadFonts} from '../../../../../common/fonts';
import {cartoonArrow} from '../../../../../common/cartoon-arrow';
import {cartoonDatabase} from '../../../../../common/cartoon-system';
import {theme} from '../../theme';
import {accent, background, heading, muted, paper, text} from '../shared/drawing';
import {warehouseSystem} from '../shared/warehouse-system';
import {recommendationSource} from '../shared/recommendation-source';

export default makeScene2D(function* (view) {
  view.fill(background);
  const title = heading('ikisini ', 'tek sistemde', ' çalıştırsak?');
  const choice = new Layout({});
  const operational = cartoonDatabase('transactions', accent);
  operational.root.position([-400, 70]);
  operational.root.scale(1.6);
  const analytical = cartoonDatabase('analytics', accent);
  analytical.root.position([400, 70]);
  analytical.root.scale(1.6);
  const link = cartoonArrow('s11-workload-separation', [-170, 70], [170, 70], accent);
  choice.add([operational.root, analytical.root, link.root, text('ETL', 30, {y: -15, fill: muted, fontFamily: theme.fontFamily.mono})]);
  view.add([title, choice]);
  yield loadFonts();
  yield* waitUntil('htap');
  yield* all(title.opacity(0, 0.2), choice.opacity(0, 0.4));
  choice.remove();
  title.children(heading('aynı uygulamada, ', 'iki workload.').children());
  const htap = new Layout({opacity: 0});
  const boundary = paper(1360, 410);
  boundary.root.position([0, 222]);
  const interfaceBar = paper(1130, 68, '#182638');
  interfaceBar.root.position([0, 112]);
  interfaceBar.root.add(text('ortak arayüz', 30));
  const name = text('HTAP', 38, {position: [0, 53], fontFamily: theme.fontFamily.mono, fill: accent});
  const workloads = [-455, 455].map((x, i) => {
    const card = paper(560, 122, '#101315');
    card.root.position([x, -173]);
    card.root.add([
      text(i ? 'hangi işlemler şüpheli?' : 'sipariş #1042', 30, {y: -25}),
      text(i ? 'çok sayıda kaydı tara' : 'oku / güncelle', 25, {y: 26, fill: accent, fontFamily: theme.fontFamily.mono}),
    ]);
    const arrow = cartoonArrow(`s12-htap-input-${i}`, [0, 0], [0, 212], accent, 0);
    arrow.root.position([x, -80]);
    arrow.root.scale(0.34);
    htap.add([card.root, arrow.root]);
    return arrow;
  });
  const promise = text('transactions + analytics', 38, {position: [0, 266], fill: accent});
  const context = text('alternatif · aynı uygulama', 25, {position: [-806, -283], offset: [-1, 0], fill: muted});
  htap.add([boundary.root, interfaceBar.root, name, promise]);
  view.add([htap, context]);
  context.opacity(0);
  yield* all(title.opacity(1, 0.3), htap.opacity(1, 0.5), context.opacity(1, 0.3));
  yield* all(...workloads.map(arrow => arrow.reveal(1, 0.3)));
  yield* all(...workloads.map(arrow => arrow.travel(0.6)));
  yield* all(...workloads.map(arrow => arrow.arrive()));
  yield* waitUntil('inside');
  yield* all(title.opacity(0, 0.2), promise.opacity(0, 0.3));
  title.children(heading('içeride ', 'farklı parçalar', ' olabilir.').children());
  const internals = new Layout({opacity: 0});
  const oltp = cartoonDatabase('OLTP', accent);
  oltp.root.position([-345, 270]);
  oltp.root.scale(0.7);
  oltp.caption.fontSize(38);
  const olap = cartoonDatabase('analytical', accent);
  olap.root.position([345, 270]);
  olap.root.scale(0.7);
  olap.caption.fontSize(38);
  const internalFlow = cartoonArrow('s12-htap-internal-update', [-219, 270], [219, 270], accent, 0);
  internals.add([oltp.root, olap.root, internalFlow.root, text('iç akış', 26, {position: [0, 190], fill: muted, opacity: () => internalFlow.reveal()})]);
  htap.add(internals);
  yield* all(title.opacity(1, 0.3), internals.opacity(1, 0.4));
  yield* internalFlow.reveal(1, 0.4);
  yield* internalFlow.travel(0.8);
  yield* internalFlow.arrive();
  yield* waitUntil('other-sources');
  yield* all(title.opacity(0, 0.2), context.opacity(0, 0.2));
  yield* all(htap.scale(0.72, 0.65), htap.position([-310, 55], 0.65));
  title.children(heading('diğer kaynaklar ', 'hala ayrı.').children());
  const outside = new Layout({opacity: 0});
  const inventory = cartoonDatabase('inventory db', accent);
  inventory.root.position([630, -112]);
  inventory.root.scale(0.66);
  inventory.caption.fontSize(37);
  const crm = paper(220, 108, '#101315');
  crm.root.position([630, 133]);
  crm.root.add([text('CRM', 28, {y: -22}), text('API', 25, {y: 24, fill: accent, fontFamily: theme.fontFamily.mono})]);
  const geo = cartoonDatabase('geo db', accent);
  geo.root.position([630, 347]);
  geo.root.scale(0.66);
  geo.caption.fontSize(37);
  outside.add([inventory.root, crm.root, geo.root]);
  view.add(outside);
  yield* all(title.opacity(1, 0.3), outside.opacity(1, 0.4));
  yield* waitUntil('combine');
  yield* title.opacity(0, 0.2);
  title.children(heading('bunları ', 'birlikte analiz etme', ' ihtiyacı sürüyor.').children());
  yield* title.opacity(1, 0.3);
  yield* waitUntil('return');
  yield* all(title.opacity(0, 0.2), htap.opacity(0, 0.4), outside.opacity(0, 0.4));
  htap.remove();
  outside.remove();
  const landscape = warehouseSystem();
  landscape.root.opacity(0);
  view.add(landscape.root);
  title.children(heading('bizim örnekte ', 'ayrı warehouse', ' ile devam.').children());
  yield* all(title.opacity(1, 0.3), landscape.root.opacity(1, 0.5));
  yield* waitUntil('specialization');
  yield* title.opacity(0, 0.2);
  title.children(heading('iş büyüdükçe ', 'uzmanlaşma', ' anlam kazanabilir.').children());
  yield* title.opacity(1, 0.3);
  yield* waitUntil('next');
  yield* all(title.opacity(0, 0.2), landscape.root.opacity(0, 0.4));
  landscape.root.remove();
  title.children(heading('peki, ', 'ürün önerisi', ' hazırlasak?').children());
  const recommendations = recommendationSource();
  recommendations.root.opacity(0);
  view.add(recommendations.root);
  yield* all(title.opacity(1, 0.3), recommendations.root.opacity(1, 0.5));
  yield* waitUntil('end');
});
