import {Layout, makeScene2D, Txt} from '@motion-canvas/2d';
import {all, waitFor, waitUntil} from '@motion-canvas/core';
import {loadFonts} from '../../../../../common/fonts';
import {cartoonArrow} from '../../../../../common/cartoon-arrow';
import {cartoonDatabase} from '../../../../../common/cartoon-system';
import {theme} from '../../theme';
import {accent, background, foreground, heading, text} from '../shared/drawing';
import {createMarket} from '../shared/market';
import {showCache} from './cache';
import {showSearch} from './search';
import {showProcessing} from './processing';

export default makeScene2D(function* (view) {
  view.fill(background);
  const bridge = new Layout({position: [-806.4, -60]});
  bridge.add([
    new Txt({offset: [-1, 0], fontFamily: theme.fontFamily.sans, fontSize: 86, fill: foreground, textWrap: false, children: [new Txt({text: 'data', fill: accent}), new Txt({text: '’yı yönetmek.'})]}),
    text('peki, nasıl?', 48, {position: [0, 130], offset: [-1, 0], fontFamily: theme.fontFamily.serif, fontStyle: 'italic'}),
  ]);
  view.add(bridge);
  yield loadFonts();
  yield* waitFor(0.4);
  yield* bridge.opacity(0, 0.45);
  bridge.remove();
  const stage = new Layout({opacity: 0});
  const title = heading('bu siparişi ', 'kaydedelim.');
  const market = createMarket();
  market.root.position([-470, 100]);
  const {root: database, top, caption: databaseCaption} = cartoonDatabase('database', accent);
  database.position([550, 110]);
  database.scale(1.4);
  databaseCaption.fontSize(28 / 1.4);
  database.opacity(0);
  database.add(text('sales db', 22, {y: -5, fontFamily: theme.fontFamily.mono}));
  const saved = text('#1042 · created', 25, {position: [550, 194], fill: accent, fontFamily: theme.fontFamily.mono, opacity: 0});
  const write = cartoonArrow('s02-save-order', [-108, 80], [354, 80], accent, 0);
  const read = cartoonArrow('s02-load-order', [354, 215], [-108, 215], accent, 0);
  const writeLabel = text('saveOrder()', 25, {position: write.pointAt(0.5).addY(-60), fontFamily: theme.fontFamily.mono, opacity: 0});
  const readLabel = text('#1042', 25, {position: read.pointAt(0.5).addY(65), fill: accent, fontFamily: theme.fontFamily.mono, opacity: 0});
  stage.add([title, market.root, database, saved, write.root, read.root, writeLabel, readLabel]);
  view.add(stage);
  yield* stage.opacity(1, 0.65);
  yield* waitUntil('store');
  yield* market.button.scale(0.96, 0.12).to(1, 0.18);
  yield* market.cart.opacity(0, 0.25);
  market.cart.remove();
  yield* database.opacity(1, 0.45);
  yield* all(write.reveal(1, 0.45), writeLabel.opacity(1, 0.3));
  yield* write.travel(0.65);
  yield* all(write.arrive(), top.stroke(accent, 0.1).to(foreground, 0.3), saved.opacity(1, 0.3));
  yield* market.receipt.opacity(1, 0.35);
  yield* waitUntil('retrieve');
  yield* all(title.opacity(0, 0.2), writeLabel.opacity(0, 0.2), market.receipt.opacity(0, 0.3));
  title.children(heading('siparişi ', 'tekrar açalım.').children());
  writeLabel.text('getOrder(1042)');
  yield* all(title.opacity(1, 0.3), writeLabel.opacity(1, 0.3));
  yield* write.travel(0.6);
  yield* all(write.arrive(), top.stroke(accent, 0.1).to(foreground, 0.3));
  yield* all(read.reveal(1, 0.4), readLabel.opacity(1, 0.3));
  yield* read.travel(0.65);
  yield* all(read.arrive(), market.receipt.opacity(1, 0.35), market.shell.stroke(accent, 0.12).to(foreground, 0.3));
  yield* waitUntil('cache');
  yield* stage.opacity(0, 0.4);
  const cache = yield* showCache(view);
  yield* waitUntil('search');
  yield* cache.root.opacity(0, 0.4);
  cache.root.remove();
  const search = yield* showSearch(view);
  yield* waitUntil('stream');
  yield* search.opacity(0, 0.4);
  search.remove();
  const processing = yield* showProcessing(view);
  yield* waitUntil('tradeoffs');
  yield* processing.opacity(0, 0.4);
  processing.remove();
  cache.market.root.opacity(0);
  cache.lookup.root.opacity(0);
  cache.hit.root.opacity(0);
  cache.lookupLabel.opacity(0);
  cache.title.children(heading('ama ', 'trafik değişti.').children());
  cache.calculation.position([-470, 85]);
  cache.calculation.scale(1.25);
  cache.calculation.opacity(1);
  cache.route.end(1);
  const fresh = text('24 dk', 46, {position: [-470, 305], fill: accent, opacity: 0, fontFamily: theme.fontFamily.mono});
  const refresh = heading('bu sonuç ne zaman ', 'yenilenecek?');
  refresh.position([-806, 410]);
  refresh.fontSize(48);
  refresh.opacity(0);
  cache.root.add([fresh, refresh]);
  view.add(cache.root);
  yield* cache.root.opacity(1, 0.5);
  yield* cache.traffic.opacity(1, 0.65);
  yield* waitFor(0.35);
  yield* fresh.opacity(1, 0.5);
  yield* waitUntil('cache-stale');
  yield* all(refresh.opacity(1, 0.4), cache.cache.face.stroke(accent, 0.4));
  yield* waitUntil('next');
  yield* cache.root.opacity(0, 0.4);
  cache.root.remove();
  title.children(heading('hangi işe, ', 'hangi araç?').children());
  write.root.opacity(1);
  read.root.opacity(0);
  writeLabel.opacity(0);
  readLabel.opacity(0);
  const responsibility = text('neyi yönetmek gerekiyor?', 44, {position: [-806, 420], offset: [-1, 0], fontFamily: theme.fontFamily.serif, fontStyle: 'italic', opacity: 0});
  stage.add(responsibility);
  yield* stage.opacity(1, 0.5);
  yield* responsibility.opacity(1, 0.5);
  yield* waitUntil('end');
});
